-- MySQL Script generated by MySQL Workbench
-- Thu Jun  1 14:24:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quickflow_db
-- -----------------------------------------------------
DROP DATABASE IF EXISTS quickflow_db;
-- -----------------------------------------------------
-- Schema quickflow_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quickflow_db` DEFAULT CHARACTER SET utf8 ;


-- -----------------------------------------------------
-- Table `quickflow_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  `hashedPassword` VARCHAR(255) NOT NULL,
  `photoProfil` VARCHAR(255) DEFAULT "http://localhost:5026/AvatarPlaceHolder.png" NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickflow_db`.`organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`organisation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom_organisation` VARCHAR(80) NOT NULL,
  `description` TEXT NULL,
  `logo` VARCHAR(255) NULL,
  `duree_des_votes` INT DEFAULT 3 NULL,
  `ratio_vote_positif` INT DEFAULT 0 NULL,
  `anonyme` TINYINT DEFAULT 0 NULL,
  `periode_idee_terminee` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `quickflow_db`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organisation_id` INT NULL,
  `titre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categorie_entreprise_id` (`organisation_id` ASC) VISIBLE,
  CONSTRAINT `fk_categorie_entreprise_id`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `quickflow_db`.`organisation` (`id`));


-- -----------------------------------------------------
-- Table `quickflow_db`.`statuts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`statuts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `etat` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `quickflow_db`.`idee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`idee` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
  `date_limite` TIMESTAMP NULL,
  `contenu` TEXT NOT NULL,
  `status` VARCHAR(45) NULL,
  `titre` VARCHAR(200) NOT NULL,
  `organisation_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `categorie_id` INT NULL,
  `utilite` TEXT NULL DEFAULT NULL,
  `contexte` TEXT NULL DEFAULT NULL,
  `benefice` TEXT NULL DEFAULT NULL,
  `inconvenient` TEXT NULL DEFAULT NULL,
  `vote` INT DEFAULT 0 NOT NULL,
  `votant` INT DEFAULT 0 NOT NULL,
  `statuts_id` INT DEFAULT 1 NULL,
  `photo_idee_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `entreprise_id_idx` (`organisation_id` ASC) VISIBLE,
  INDEX `categorie_id_idx` (`categorie_id` ASC) VISIBLE,
  INDEX `fk_status_id_idx` (`statuts_id` ASC) VISIBLE,
  INDEX `fk_photo_idee_id_idx` (`photo_idee_id` ASC) VISIBLE,
  CONSTRAINT `organisation_id`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `quickflow_db`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `quickflow_db`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categorie_id`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `quickflow_db`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statuts_id`
    FOREIGN KEY (`statuts_id`)
    REFERENCES `quickflow_db`.`statuts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_photo_idee_id`
    FOREIGN KEY (`photo_idee_id`)
    REFERENCES `quickflow_db`.`photo_idee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickflow_db`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`commentaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  `date` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `user_id` INT NULL,
  `idee_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commentaire_user_id` (`user_id` ASC) VISIBLE,
  INDEX `fk_idee_id_idx` (`idee_id` ASC) VISIBLE,
  CONSTRAINT `fk_commentaire_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `quickflow_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_idee_id`
    FOREIGN KEY (`idee_id`)
    REFERENCES `quickflow_db`.`idee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quickflow_db`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `quickflow_db`.`organisation_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`organisation_user` (
  `organisation_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `role_id` INT DEFAULT 1 NOT NULL,
  `check_role` TINYINT DEFAULT 0 NOT NULL,
  INDEX `fk_entreprise_user_entreprise_id` (`organisation_id` ASC) VISIBLE,
  INDEX `fk_entreprise_user_user_id` (`user_id` ASC) VISIBLE,
  INDEX `fk_role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_entreprise_user_entreprise_id`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `quickflow_db`.`organisation` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entreprise_user_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `quickflow_db`.`user` (`id`),
  CONSTRAINT `fk_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `quickflow_db`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



-- -----------------------------------------------------
-- Table `quickflow_db`.`follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`follow` (
  `idee_id` INT NULL,
  `user_id` INT NULL,
  `follow_idee` TINYINT DEFAULT 0 NOT NULL,
  INDEX `fk_follow_idee_id` (`idee_id` ASC) VISIBLE,
  INDEX `fk_follow_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_follow_idee_id`
    FOREIGN KEY (`idee_id`)
    REFERENCES `quickflow_db`.`idee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_follow_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `quickflow_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `quickflow_db`.`like_commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`like_commentaire` (
  `commentaire_id` INT NULL,
  `user_id` INT NULL,
  `nb_like_commentaire` TINYINT DEFAULT 0 NOT NULL,
  INDEX `fk_like_commentaire_commentaire_id` (`commentaire_id` ASC) VISIBLE,
  INDEX `fk_like_commentaire_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_like_commentaire_commentaire_id`
    FOREIGN KEY (`commentaire_id`)
    REFERENCES `quickflow_db`.`commentaire` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_like_commentaire_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `quickflow_db`.`user` (`id`));


-- -----------------------------------------------------
-- Table `quickflow_db`.`like_idee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`like_idee` (
  `idee_id` INT NULL,
  `user_id` INT NULL,
  `status` INT DEFAULT 0 NULL,
  `nb_like_idee` TINYINT DEFAULT 0  NOT NULL,
  INDEX `fk_like_idee_idee_id` (`idee_id` ASC) VISIBLE,
  INDEX `fk_like_idee_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_like_idee_idee_id`
    FOREIGN KEY (`idee_id`)
    REFERENCES `quickflow_db`.`idee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_like_idee_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `quickflow_db`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- allez commit stp

-- -----------------------------------------------------
-- Table `quickflow_db`.`photo_idee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quickflow_db`.`photo_idee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lien` VARCHAR(255) NULL,
  `idea_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_idea_id_idx` (`idea_id` ASC) VISIBLE,
  CONSTRAINT `fk_idea_id`
    FOREIGN KEY (`idea_id`)
    REFERENCES `quickflow_db`.`idee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



-- -----------------------------------------------------
-- Ajout des utilisateurs
-- -----------------------------------------------------



INSERT INTO `quickflow_db`.`user` (`nom`,`prenom`,`hashedPassword`,`email`) VALUES ("Démo","Antoine","$argon2id$v=19$m=65536,t=5,p=1$4zMzds3n0uIfK3uHfjYibw$t87yBL8+o+DD4Ecog4thg7ImvHuclEXbUE3NfLl7n5Y","demo@demo.com");
INSERT INTO `quickflow_db`.`user` (`nom`,`prenom`,`hashedPassword`,`email`,`photoProfil`) VALUES ("Douay","Sébastien","$argon2id$v=19$m=65536,t=5,p=1$Js/jri9+1b89m1rTDzaxqQ$4LPccE+i+aEt/xnjadda/aE1QRoKPmDG7YVvz6fV3i8","Sébastien@outlook.com","http://localhost:5026/photo/user/2.jpg");
INSERT INTO `quickflow_db`.`user` (`nom`,`prenom`,`hashedPassword`,`email`,`photoProfil`) VALUES ("Desbrosses","Vincent","$argon2id$v=19$m=65536,t=5,p=1$72P9rtmkBOQ3dqwQUuzd9g$/7908Oy8UehCrjVRqhM/JqEmbFvOrbFSGMbthOmhG3Q","vincedsb@gmail.com","http://localhost:5026/photo/user/3.jpg");
INSERT INTO `quickflow_db`.`user` (`nom`,`prenom`,`hashedPassword`,`email`,`photoProfil`) VALUES ("Beillevert","J-E","$argon2id$v=19$m=65536,t=5,p=1$tFndHKbA5ELAUoqfi5GvRA$n/phvpDl7zRxeU96EemV7giZr2TOIyRMkXElYU2C3Ls","J-E@outlook.com","http://localhost:5026/photo/user/4.jpg");
INSERT INTO `quickflow_db`.`user` (`nom`,`prenom`,`hashedPassword`,`email`,`photoProfil`) VALUES ("Angibaud","Tommy","$argon2id$v=19$m=65536,t=5,p=1$oW2yi9pnM+9jSyWSzlJqHg$xh6J2sqBcn9F+Tn3AAuOTuWiCrZq3Xwbo5mEVPd4muQ","Tommy.Angibaud@outlook.com","http://localhost:5026/photo/user/5.jpg");



-- -----------------------------------------------------
-- Ajout des organisations
-- -----------------------------------------------------


INSERT INTO `quickflow_db`.`organisation` (`nom_organisation`,`description`,`logo`,`duree_des_votes`,`ratio_vote_positif`,`anonyme`,`periode_idee_terminee`) VALUES ("Wild Code School","Centre de formation","http://localhost:5026/photo/organisation/wildcodeschool.png",30,35,0,60);
INSERT INTO `quickflow_db`.`organisation` (`nom_organisation`,`description`,`logo`,`duree_des_votes`,`ratio_vote_positif`,`anonyme`,`periode_idee_terminee`) VALUES ("Vacances","Notre prochaine destination","http://localhost:5026/photo/organisation/vague.jpg",30,2,0,60);
INSERT INTO `quickflow_db`.`organisation` (`nom_organisation`,`description`,`logo`,`duree_des_votes`,`ratio_vote_positif`,`anonyme`,`periode_idee_terminee`) VALUES ("Club photo","Choisir les prochains contras ensemble","http://localhost:5026/photo/organisation/photo.jpg",30,10,0,60);

-- -----------------------------------------------------
-- Table `quickflow_db`.`categorie`
-- -----------------------------------------------------

INSERT INTO `quickflow_db`.`categorie` (`titre`) VALUES ("parking");
INSERT INTO `quickflow_db`.`categorie` (`titre`) VALUES ("salle de repos");
INSERT INTO `quickflow_db`.`categorie` (`titre`) VALUES ("cantine");
INSERT INTO `quickflow_db`.`categorie` (`titre`) VALUES ("budget");



-- -----------------------------------------------------
-- Ajout des Status
-- -----------------------------------------------------

INSERT INTO `quickflow_db`.`statuts` (`etat`) VALUES ("À voter");
INSERT INTO `quickflow_db`.`statuts` (`etat`) VALUES ("Décisions en cours");
INSERT INTO `quickflow_db`.`statuts` (`etat`) VALUES ("Terminé");


-- -----------------------------------------------------
-- Ajout des idee
-- -----------------------------------------------------

SET FOREIGN_KEY_CHECKS=0;
INSERT INTO `quickflow_db`.`idee` (`titre`,`date`,`date_limite`,`contenu`,`status`,`utilite`,`contexte`,`benefice`,`inconvenient`,`vote`,`votant`,`statuts_id`,`organisation_id`,`photo_idee_id`, `user_id`) VALUES ("Robots-Professeurs",DATE("2023-06-05"),TIMESTAMP("2024-07-20","03:12:45"),"Imaginons l'introduction de robots animés par l'IA dans la salle de classe. Ils pourraient adapter leur enseignement aux besoins individuels de chaque étudiant, fournir des retours immédiats et même apprendre de nouvelles matières.","Validé","Utilité","Description de l’idée","Ça coûterait moins cher en salaires","Il faut inventer les robots d'abord",36,25,1,1,1,1);
INSERT INTO `quickflow_db`.`idee` (`titre`,`date`,`date_limite`,`contenu`,`status`,`utilite`,`contexte`,`benefice`,`inconvenient`,`vote`,`votant`,`statuts_id`,`organisation_id`,`photo_idee_id`, `user_id`) VALUES ("Prendre des photos de la promo",DATE("2023-06-05"),TIMESTAMP("2024-07-01","07:15:30"),"Apporter un appareil photo instantané pour faire des photos de chaque membre de la promo, afin de les afficher sur les murs, comme les autres promos.","Validé","Montrer à quel point on est heureux de faire la formation.","On est en formation","Team building","Coute 20 €",33,42,2,1,1,1);
INSERT INTO `quickflow_db`.`idee` (`titre`,`date`,`date_limite`,`contenu`,`status`,`utilite`,`contexte`,`benefice`,`inconvenient`,`vote`,`votant`,`statuts_id`,`organisation_id`,`photo_idee_id`, `user_id`) VALUES ("Ne pas faire le hackathon 2",DATE("2023-06-05"),TIMESTAMP("2024-07-06","22:45:55"),"Vu que le projet 3 est passionnant et va être présenté au titre, nous demandons de zapper le hackathon 2 pour se concentrer sur le projet.","Refusé","Obtention du titre","Nous sommes étudiants et voulons éviter le chommage.","Obtention du titre","Les jours se suivent et se ressemblent.",15,25,3,1,1,1);
INSERT INTO `quickflow_db`.`idee` (`titre`,`date`,`date_limite`,`contenu`,`status`,`utilite`,`contexte`,`benefice`,`inconvenient`,`vote`,`votant`,`statuts_id`,`organisation_id`,`photo_idee_id`, `user_id`) VALUES ("Une piscine à la Wild",DATE("2023-06-09"),TIMESTAMP("2024-09-05","07:05:16"),"Dans une démarche avant-gardiste et résolument tournée vers l'avenir, notre école d'informatique envisage d'ajouter un tout nouvel élément à son infrastructure : une piscine. Cette piscine n'est pas une installation de loisirs ordinaire, elle représente une véritable innovation en matière d'apprentissage et de technologie. L'idée est d'utiliser l'eau de la piscine comme un moyen naturel et efficace de refroidissement pour les serveurs de l'école. Ainsi, les étudiants ne se contenteraient pas d'apprendre les principes fondamentaux de l'informatique et du codage, mais seraient également initiés à des méthodes innovantes de gestion de l'énergie et de maintenance de l'infrastructure informatique. C'est une occasion pour eux de comprendre les défis environnementaux de l'industrie de l'informatique. Qui plus est, cette piscine pourrait offrir un lieu de détente bien mérité, mêlant travail intellectuel intense et relaxation, pour stimuler l'efficacité et le bien-être de nos étudiants.","Validé","Utilité","Context","benefice","inconvenient",15,25,1,1,1,1);
INSERT INTO `quickflow_db`.`idee` (`titre`,`date`,`date_limite`,`contenu`,`status`,`utilite`,`contexte`,`benefice`,`inconvenient`,`vote`,`votant`,`statuts_id`,`organisation_id`,`photo_idee_id`, `user_id`) VALUES ("Tripler le salaire de tout le monde ça serait vraiment sympa car ça permettrait de ne plus avoir à se soucier du budget et se concentrer sur notre apprentissage uniquement",DATE("2023-06-09"),TIMESTAMP("2024-09-19","22:11:54"),"Tripler le salaire de tout le monde","Validé","Utilité","Context","Tout le monde serait content.","Ça coûte che.",13,21,1,1,1,1);
INSERT INTO `quickflow_db`.`idee` (`titre`,`date`,`date_limite`,`contenu`,`status`,`utilite`,`contexte`,`benefice`,`inconvenient`,`vote`,`votant`,`statuts_id`,`organisation_id`,`photo_idee_id`,`user_id`) VALUES ("Classe de Clavier-Canapé",DATE("1983-06-05"),TIMESTAMP("2024-10-03","15:39:10"),"En transformant les claviers en canapés confortables, les étudiants pourraient coder dans une position détendue. Cela pourrait également promouvoir la créativité et la résolution innovante de problèmes.","Validé","Utilité","Context","Gain de sérénité pour les étudiants","Les claviers ne pourraient pas être très ergonomiques",10,13,1,1,1,1);
INSERT INTO `quickflow_db`.`idee` (`titre`,`date`,`date_limite`,`contenu`,`status`,`utilite`,`contexte`,`benefice`,`inconvenient`,`vote`,`votant`,`statuts_id`,`organisation_id`,`photo_idee_id`,`user_id`) VALUES ("Remettre les paniers de fruits",DATE("2023-06-05"),TIMESTAMP("2024-07-02","18:25:45"),"C'était cool au début mais ça s'est vite arrêté ^^'","Validé","Utilité","Description de l’idée","benefice","inconvenient",18,20,2,1,1,1);
INSERT INTO `quickflow_db`.`idee` (`titre`,`date`,`date_limite`,`contenu`,`status`,`utilite`,`contexte`,`benefice`,`inconvenient`,`vote`,`votant`,`statuts_id`,`organisation_id`,`photo_idee_id`,`user_id`) VALUES ("Brasser une bière pour la fin de l'année",DATE("2021-06-05"),TIMESTAMP("2024-07-08","16:17:40"),"Moyennement un budget d'environs 5 €, est serait possible de brasser notre propre bière, qu'en dîtes-vous ?","Validé","Utilité","Description de l’idée","benefice","inconvenient",15,25,3,1,1,1);
INSERT INTO `quickflow_db`.`idee` (`titre`,`date`,`date_limite`,`contenu`,`status`,`utilite`,`contexte`,`benefice`,`inconvenient`,`vote`,`votant`,`statuts_id`,`organisation_id`,`photo_idee_id`,`user_id`) VALUES ("Codage par télépathie",DATE("2025-06-05"),TIMESTAMP("2024-10-20","19:45:38"),"Intégrer une technologie de lecture de pensée qui permettrait aux étudiants de coder simplement en pensant à la syntaxe. Un moyen de maximiser l'efficacité et d'économiser l'énergie physique.","Validé","Utilité","Context","Gain de productivité","Difficulté de couper du travail le ",1,2,1,1,1,1);
INSERT INTO `quickflow_db`.`idee` (`titre`,`date`,`date_limite`,`contenu`,`status`,`utilite`,`contexte`,`benefice`,`inconvenient`,`vote`,`votant`,`statuts_id`,`organisation_id`,`photo_idee_id`,`user_id`) VALUES ("Café-télé hebdomadaire",DATE("2015-06-05"),TIMESTAMP("2024-07-04","12:36:10"),"Faire un groupe support Café-télé toutes les semaines.","Validé","Utilité","Description de l’idée","benefice","inconvenient",28,44,2,1,1,1);
INSERT INTO `quickflow_db`.`idee` (`titre`,`date`,`date_limite`,`contenu`,`status`,`utilite`,`contexte`,`benefice`,`inconvenient`,`vote`,`votant`,`statuts_id`,`organisation_id`,`photo_idee_id`,`user_id`) VALUES ("Faire une soirée d'intégration",DATE("2007-06-05"),TIMESTAMP("2024-07-09","14:28:35"),"Se retrouver vendredi pour la soirée d'intégration.","Validé","Utilité","Description de l’idée","benefice","inconvenient",15,25,3,1,1,1);


-- -----------------------------------------------------
-- Table `quickflow_db`.`commentaire`
-- -----------------------------------------------------


INSERT INTO `quickflow_db`.`commentaire` (`description`,`user_id`,`idee_id`) VALUES ("BLALBLALBLABLA",1,1);
INSERT INTO `quickflow_db`.`commentaire` (`description`,`user_id`,`idee_id`) VALUES ("BLALBLALBLABLA",4,2);
INSERT INTO `quickflow_db`.`commentaire` (`description`,`user_id`,`idee_id`) VALUES ("BLALBLALBLABLA",2,3);


-- -----------------------------------------------------
-- Table `quickflow_db`.`follow`
-- -----------------------------------------------------

INSERT INTO `quickflow_db`.`follow` (`follow_idee`,`idee_id`,`user_id`) VALUES (0,1,1);
INSERT INTO `quickflow_db`.`follow` (`follow_idee`,`idee_id`,`user_id`) VALUES (0,1,2);
INSERT INTO `quickflow_db`.`follow` (`follow_idee`,`idee_id`,`user_id`) VALUES (1,1,3);


-- -----------------------------------------------------
-- Table `quickflow_db`.`like_commentaire`
-- -----------------------------------------------------


INSERT INTO `quickflow_db`.`like_commentaire` (`nb_like_commentaire`,`commentaire_id`,`user_id`) VALUES (0,1,1);
INSERT INTO `quickflow_db`.`like_commentaire` (`nb_like_commentaire`,`commentaire_id`,`user_id`) VALUES (0,1,2);
INSERT INTO `quickflow_db`.`like_commentaire` (`nb_like_commentaire`,`commentaire_id`,`user_id`) VALUES (1,1,3);
INSERT INTO `quickflow_db`.`like_commentaire` (`nb_like_commentaire`,`commentaire_id`,`user_id`) VALUES (1,1,4);
INSERT INTO `quickflow_db`.`like_commentaire` (`nb_like_commentaire`,`commentaire_id`,`user_id`) VALUES (1,2,1);
INSERT INTO `quickflow_db`.`like_commentaire` (`nb_like_commentaire`,`commentaire_id`,`user_id`) VALUES (1,2,2);
INSERT INTO `quickflow_db`.`like_commentaire` (`nb_like_commentaire`,`commentaire_id`,`user_id`) VALUES (1,2,3);

-- -----------------------------------------------------
-- Table `quickflow_db`.`like_idee`
-- -----------------------------------------------------


INSERT INTO `quickflow_db`.`like_idee` (`idee_id`,`user_id`, `status`, `nb_like_idee`) VALUES (1,1,1,1);
INSERT INTO `quickflow_db`.`like_idee` (`idee_id`,`user_id`, `status`, `nb_like_idee`) VALUES (2,1,1,1);
INSERT INTO `quickflow_db`.`like_idee` (`idee_id`,`user_id`, `status`, `nb_like_idee`) VALUES (4,1,2,2);
INSERT INTO `quickflow_db`.`like_idee` (`idee_id`,`user_id`, `status`, `nb_like_idee`) VALUES (5,1,0,3);
INSERT INTO `quickflow_db`.`like_idee` (`idee_id`,`user_id`, `status`, `nb_like_idee`) VALUES (6,1,0,4);
INSERT INTO `quickflow_db`.`like_idee` (`idee_id`,`user_id`, `status`, `nb_like_idee`) VALUES (7,1,2,4);
INSERT INTO `quickflow_db`.`like_idee` (`idee_id`,`user_id`, `status`, `nb_like_idee`) VALUES (9,1,1,4);
INSERT INTO `quickflow_db`.`like_idee` (`idee_id`,`user_id`, `status`, `nb_like_idee`) VALUES (10,1,0,4);




-- -----------------------------------------------------
-- Table `quickflow_db`.`role`
-- -----------------------------------------------------


INSERT INTO `quickflow_db`.`role` (`role`) VALUES ("admin");
INSERT INTO `quickflow_db`.`role` (`role`) VALUES ("décisionnaire");
INSERT INTO `quickflow_db`.`role` (`role`) VALUES ("supprimer idée");
INSERT INTO `quickflow_db`.`role` (`role`) VALUES ("supprimer commentaire");

-- -----------------------------------------------------
-- Table `quickflow_db`.`organisation_user`
-- -----------------------------------------------------

INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (1,1,1,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (1,1,2,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (1,1,3,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (1,1,4,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (1,2,3,0);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (1,2,1,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (2,1,1,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (2,1,2,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (2,1,3,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (2,1,4,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (3,1,1,0);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (3,1,2,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (3,1,3,0);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (3,1,4,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (4,1,1,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (4,1,2,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (4,1,3,0);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (4,1,4,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (5,1,1,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (5,1,2,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (5,1,3,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (5,1,4,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (5,2,2,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (5,2,1,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (5,3,5,1);
INSERT INTO `quickflow_db`.`organisation_user` (`user_id`,`organisation_id`,`role_id`,`check_role`) VALUES (5,3,1,1);

-- -----------------------------------------------------
-- Table `quickflow_db`.`photo_idee`
-- -----------------------------------------------------

INSERT INTO `quickflow_db`.`photo_idee` (`lien`,`idea_id`) VALUES ("http://localhost:5026/assets/images/ideas/1.jpeg",1);
INSERT INTO `quickflow_db`.`photo_idee` (`lien`,`idea_id`) VALUES ("http://localhost:5026/assets/images/ideas/2.jpeg",2);
INSERT INTO `quickflow_db`.`photo_idee` (`lien`,`idea_id`) VALUES ("http://localhost:5026/assets/images/ideas/3.jpeg",3);
INSERT INTO `quickflow_db`.`photo_idee` (`lien`,`idea_id`) VALUES ("http://localhost:5026/assets/images/ideas/4.jpeg",4);
INSERT INTO `quickflow_db`.`photo_idee` (`lien`,`idea_id`) VALUES ("http://localhost:5026/assets/images/ideas/5.jpeg",5);
INSERT INTO `quickflow_db`.`photo_idee` (`lien`,`idea_id`) VALUES ("http://localhost:5026/assets/images/ideas/6.jpeg",6);
INSERT INTO `quickflow_db`.`photo_idee` (`lien`,`idea_id`) VALUES ("http://localhost:5026/assets/images/ideas/7.jpeg",7);
INSERT INTO `quickflow_db`.`photo_idee` (`lien`,`idea_id`) VALUES ("http://localhost:5026/assets/images/ideas/8.jpeg",8);
INSERT INTO `quickflow_db`.`photo_idee` (`lien`,`idea_id`) VALUES ("http://localhost:5026/assets/images/ideas/9.jpeg",9);
INSERT INTO `quickflow_db`.`photo_idee` (`lien`,`idea_id`) VALUES ("http://localhost:5026/assets/images/ideas/10.jpeg",10);
INSERT INTO `quickflow_db`.`photo_idee` (`lien`,`idea_id`) VALUES ("http://localhost:5026/assets/images/ideas/11.jpeg",11);

USE `quickflow_db`;